feeds/mountainline.com.dmfr.json

Missoula Urban Transportation District

---

feeds/circulatordashboard.dc.gov.dmfr.json

DC Circulator

---

feeds/capitolcorridor.org.dmfr.json

https://www.capitolcorridor.org/developer_resources/

update Capitol Corridor

---

feeds/sanjoaquinrtd.com.dmfr.json

http://sanjoaquinrtd.com/developer-portal/#GTFS

San Joaquin RTD

---

feeds/tularecog.org.dmfr.json

https://www.tularecog.org/gtfs/

Tulare County, California

---

feeds/511.org.dmfr.json

SFO shuttle buses and AirTrain

---

feeds/github.com.dmfr.json
feeds/s3.amazonaws.com.dmfr.json

Tompkins Consolidated Area Transit

---

feeds/s3.amazonaws.com.dmfr.json
feeds/tcatbus.com.dmfr.json

Tompkins County TCAT RT

---

feeds/portauthority.org.dmfr.json

Add realtime feeds for Port Authority of Allegheny County

---

feeds/trentinotrasporti.it.dmfr.json

https://www.trentinotrasporti.it/open-data/
related to https://github.com/OpenMobilityData/OpenMobilityData-Public/issues/94

Trentino Transporti

---

feeds/oregon-gtfs.com.dmfr.json

Remove `f-9rb-eugenetocoosbay~or~us`

---

feeds/oregon-gtfs.com.dmfr.json

remove `f-9rb-valleyretriever~or~us`

---

feeds/github.com.dmfr.json

https://github.com/septadev/GTFS/releases/tag/v202004061

latest SEPTA feed

---

README.md

update readme & instructions for adding feeds

---

feeds/api.goswift.ly.dmfr.json

Reopening #62 to create a DMFR.json file for Swiftly-provided realtime information

Add Swiftly's GTFS-rt feeds for RTA Maryland

---

feeds/trilliumtransit.com.dmfr.json

this time with tildas in the OnestopID

Added breckenridgefreeride

---

feeds/mjcaction.com.dmfr.json

from https://mjcaction.com/satisfied-clients.html

update Transnnovation (MJC) feeds

---

feeds/nationalrtap.org.dmfr.json

https://www.bata.net/customer-service/gtfs-data.html

Bay Area Transportation Authority (Michigan)

---

feeds/opendata.transport.nsw.gov.au.dmfr.json

from https://opendata.transport.nsw.gov.au/node/334/exploreapi#/

New South Whales (Australia)

---

feeds/parkcity.org.dmfr.json

from https://www.transitwiki.org/TransitWiki/index.php/Publicly-accessible_public_transportation_data

Park City (Utah)

---

feeds/mjcaction.com.dmfr.json
feeds/transitland.github.com.dmfr.json

Island Transit

---

feeds/transitland.github.com.dmfr.json

uploaded in https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/67

Interline created feeds for DC area

---

operators/o-9q8-samtrans.json
operators/o-9q8y-sfmta.json
operators/o-9q8yy-missionbaytma.json
operators/o-9q8zm-blue~goldfleet.json
operators/o-9q8zr-tidelinewatertaxi.json
operators/o-9q9-bart.json
operators/o-9q9-caltrain.json
operators/o-9qb-goldengatetransit.json

to test the "crosswalk" on the tlv2 website

some OpenMobilityData provider IDs

---

feeds/trilliumtransit.com.dmfr.json

Apologies for the many PRs lately. We've been implementing many new GTFS feeds for clients. There will probably be more to come later this month.

Added Arvin Transit and Alhambra Community Transit

---

feeds/modestoareaexpress.com.dmfr.json
feeds/trilliumtransit.com.dmfr.json
operators/o-9q9-modestoareaexpress.json

merging together two feed records, adding some more RT endpoints, and adding crosswalk IDs for the operator record
//cc @mcplanner

Modesto Area Express

---

.github/workflows/update-gbfs.yml
feeds/nabsa.github.com.dmfr.json
scripts/convert-gbfs-csv-to-dmfr.py

closes GBFS updater script should validate feed file #171

more robust GBFS feed list updating

---

feeds/macog.com.dmfr.json
operators/o-bttgg-macog.json
operators/o-macog.json

Hat tip to https://www.transitwiki.org/TransitWiki/index.php/Publicly-accessible_public_transportation_data for a link to the MACOG feed.
PS... I couldn't find a link for South Bend Transpo...

Add Interurban Trolley in Elkhart, IN

---

feeds/rtcquebec.ca.dmfr.json

from https://www.rtcquebec.ca/donnees-ouvertes

RTC Quebec

---

feeds/agenziatpl.it.dmfr.json

http://www.agenziatpl.it/open-data/gtfs

Agenzia TPL (Milan)

---

.github/workflows/update-gbfs.yml
.github/workflows/validate.yml
feeds/nabsa.github.com.dmfr.json
feeds/nvbw.de.dmfr.json
feeds/trilliumtransit.com.dmfr.json
scripts/validate-feeds.py

from https://github.com/interline-io/transitland-lib

switch GitHub Actions CI to using latest public version of transitland-lib

---

feeds/nationalrtap.org.dmfr.json
feeds/tularecog.org.dmfr.json

https://tularecog.org/tcag/data-gis-modeling/gtfs-data/

Tulare COG updates

---

feeds/transitland.github.com.dmfr.json

see https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/77

latest batch of Interline created feeds

---

feeds/lextran.com.dmfr.json

new Lextran URL

---

feeds/github.com.dmfr.json

https://github.com/septadev/GTFS/releases/tag/v202104052

latest SEPTA

---

feeds/gitlab.com.dmfr.json
feeds/trilliumtransit.com.dmfr.json

Removed Lynwood from Gitlab and added it Trillium.

Added Lynwood Trolley

---

feeds/transitland.github.com.dmfr.json

uploaded in https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/80

two new Interline feeds

---

feeds/citycommbus.com.dmfr.json
feeds/trilliumtransit.com.dmfr.json

City of Commerce

---

feeds/mjcaction.com.dmfr.json

from https://mjcaction.com/satisfied-clients.html

Mountain Express

---

feeds/trilliumtransit.com.dmfr.json

Added La Puente LINK, El Segundo Transportation, Catalina Flyer, and Farmville Area Bus.
Fixed fetch URL for taft-ca-us

Added 4 feeds

---

feeds/avta.com.dmfr.json

Antelope Valley Transit Authority

---

feeds/transitland.github.com.dmfr.json

https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/84

Berks Area Regional Transportation Authority (BARTA)

---

feeds/github.com.dmfr.json

unofficlal feed from https://github.com/laidig/rioc-gtfs

Roosevelt Island Tramway

---

feeds/transitland.github.com.dmfr.json

https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/85

Red Rose Transit Authority (RRTA)

---

feeds/transitland.github.com.dmfr.json

fixing a bad Onestop ID

---

feeds/mecatran.com.dmfr.json
feeds/mjcaction.com.dmfr.json

https://www.slocity.org/government/department-directory/public-works/slo-transit/general-service-information

City of San Luis Obispo Transit

---

feeds/transitland.github.com.dmfr.json

https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/89

Hele-On Bus

---

feeds/cleanairexpress.com.dmfr.json

received via email
http://www.cleanairexpress.com/gtfs.htm

Clean Air Express

---

feeds/tfwm.org.uk.dmfr.json

received via email
https://api-portal.tfwm.org.uk/

Transport for West Midlands

---

feeds/apps.kitsaptransit.com.dmfr.json

http://pride.kitsaptransit.com/gtfs/google_transit.zip

Update static URL

---

feeds/transitland.github.com.dmfr.json

https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/88
https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/87

adding two new feeds from `transitland/gtfs-archives-not-hosted-elsewhere`

---

feeds/trilliumtransit.com.dmfr.json

Clackamas County, District Three, and Benson are new agencies. 
Skamania County/Gorge WET existed previously on our server, but they've moved to a new URL.

Add three new agencies, reconfigure one agency

---

feeds/durangogov.org.dmfr.json
feeds/greeleygov.com.dmfr.json

https://colorado-gtfs.trilliumtransit.com/

Colorado feeds

---

feeds/oregon-gtfs.com.dmfr.json

Moved fetch link for Bluestar to "historic"

---

feeds/itsmarta.com.dmfr.json

https://www.itsmarta.com/app-developer-resources.aspx

MARTA (Atlanta) RT endpoints

---

feeds/frederickcountymd.gov.dmfr.json

updated URL for Frederick County

---

feeds/mecatran.com.dmfr.json
feeds/transitland.github.com.dmfr.json

agency provided feed for Greensboro, NC

---

feeds/trilliumtransit.com.dmfr.json

Tulare TCaT flex

---

feeds/api.transloc.com.dmfr.json
feeds/buncombecounty.org.dmfr.json
feeds/cityofclarksville.com.dmfr.json
feeds/content.mankatomn.gov.dmfr.json
feeds/fourcountytransit.org.dmfr.json
feeds/freedom-transit.org.dmfr.json
feeds/highpointnc.gov.dmfr.json
feeds/mct.org.dmfr.json
feeds/metracolumbus.com.dmfr.json
feeds/mjcaction.com.dmfr.json
feeds/oregon-gtfs.com.dmfr.json
feeds/whereispdrta.com.dmfr.json

Added Curry Public Transit to Oregon-gtfs.com

---

feeds/data.buenosaires.gob.ar.dmfr.json

- https://data.buenosaires.gob.ar/dataset/trenes-gtfs
- https://data.buenosaires.gob.ar/dataset/subte-gtfs
- https://data.buenosaires.gob.ar/dataset/colectivos-gtfs

Buenos Aires

---

feeds/marintransit.org.dmfr.json

Update Marin Transit static GTFS URL

Add Marin Transit GTFS Realtime URLs

---

feeds/oregon-gtfs.com.dmfr.json

Updating feeds listed on http://oregon-gtfs.com/

Oregon GTFS feeds managed by Trillium

---

feeds/culvercity.org.dmfr.json

https://www.culvercity.org/City-Hall/Departments/IT/Download-GIS-Data

Culver City

---

feeds/transloc.com.dmfr.json
feeds/trilliumtransit.com.dmfr.json

NCSU Wolfline

---

feeds/rushtrail.app.dmfr.json

**Source of Data**: LTA (https://datamall.lta.gov.sg/content/dam/datamall/datasets/LTA_DataMall_API_User_Guide.pdf)
**Agencies**: LTA, SMRT, SBST, TTS, GAS 
**Content**: More exhaustive list of SG Bus Services 
(includes Trunk, Feeder, ShortTrips (end with A), Jurong Industrial Service, Express, City Direct, Night, Chinatown Direct, Cross Border Services, Resorts World Sentosa Bus services)
(for more info: https://en.wikipedia.org/wiki/Public_buses_of_Singapore)
_For any questions, feel free to contact songyan@rushowl.sg_ 👍

Update on the Singapore Transit Data 

---

feeds/tularecog.org.dmfr.json

https://tularecog.org/tcag/data-gis-modeling/gtfs-data/

Tulare County Regional Transit Agency (TCRTA)

---

feeds/gobrightline.com.dmfr.json

Brightline

---

feeds/sacrt.com.dmfr.json

http://www.sacrt.com/schedules/gtfs.aspx

Sacramento Regional Transit

---

feeds/data.smtd.org.dmfr.json

Sangamon Mass Transit District

---

feeds/poa.br.dmfr.json

https://dadosabertos.poa.br/dataset/gtfs

Porto Alegre

---

feeds/stops.lt.dmfr.json

Adding two more GTFS feeds of two Lithuanian cities:
- Siauliai
- Alytus

GTFS feeds of Siauliai and Alytus (Lithuania)

---

feeds/metlink.org.nz.dmfr.json

Hiya,
First PR, everything look all good?
Thanks!

Updating Metlink feed URL

---

feeds/nabsa.github.com.dmfr.json
feeds/openmobilityfoundation.github.com.dmfr.json

```
fd -e dmfr.json -x transitland dmfr format --save {}
```

re-running opinionated DMFR format

---

feeds/ltconline.ca.dmfr.json

https://www.londontransit.ca/open-data/

London Transit

---

feeds/ztp.krakow.pl.dmfr.json

Kraków, Poland

---

feeds/arcgis.com.dmfr.json

Fredericksburg Regional Transit

---

feeds/navitia.opendatasoft.com.dmfr.json
feeds/tmb.cat.dmfr.json

https://developer.tmb.cat/data/gtfs

Transports Metropolitans de Barcelona

---

feeds/suntran.com.dmfr.json
feeds/transitland.github.com.dmfr.json
feeds/trilliumtransit.com.dmfr.json

related to https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/105

multiple Suntran entries

---

feeds/tram.cat.dmfr.json

TRAM (Barcelona)

---

feeds/bizizmir.com.dmfr.json

https://acikveri.bizizmir.com/dataset/toplu-ulasim-gtfs-verileri

Izmir, Turkey

---

feeds/zet.hr.dmfr.json

First time I've ever done anything like this, hope this is ok.

Added Zagrebački električni tramvaj GTFS RT

---

feeds/datatools-nysdot.dmfr.json
feeds/nicebus.com.dmfr.json

```
http https://s3.amazonaws.com/datatools-511ny/public/index.html | pup 'a attr{href}' | pbcopy
```

New York State

---

.github/workflows/update-gbfs.yml
.github/workflows/update-mds.yml
.github/workflows/validate.yml

https://github.com/interline-io/transitland-lib/pull/196

use latest transitland-lib for opinionated format

---

feeds/bkk.hu.dmfr.json
feeds/dev.hsl.fi.dmfr.json
feeds/dft.gov.uk.dmfr.json
feeds/gtfs.irail.be.dmfr.json
feeds/gtfs.mot.gov.il.dmfr.json
feeds/gtt.to.it.dmfr.json
feeds/mkuran.pl.dmfr.json
feeds/opendata.iprpraha.cz.dmfr.json
feeds/opendata.transport.nsw.gov.au.dmfr.json
feeds/opentransportdata.swiss.dmfr.json
feeds/reis.ruter.no.dmfr.json
feeds/transport.orgp.spb.ru.dmfr.json
feeds/vbb.de.dmfr.json

Reverts transitland/transitland-atlas#505

Revert "larger European feeds"

---

feeds/downtownny.com.dmfr.json
feeds/mjcaction.com.dmfr.json

http://www.downtownny.com/getting-around/downtown-connection

Downtown Connection

---

feeds/transitland.github.com.dmfr.json

https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/109

HARTransit

---

feeds/ridelbt.com.dmfr.json

https://ridelbt.com/gtfs-feed/

Long Beach Transit

---

feeds/511.org.dmfr.json

SF Bay Area Regional Realtime Feed

---

feeds/transitdata.phoenix.gov.dmfr.json

https://www.phoenixopendata.com/organization/public-transit

Phoenix Valley Metro

---

feeds/go-metro.com.dmfr.json

https://www.go-metro.com/about-metro/developer-data

Southwest Ohio Regional Transit Authority (SORTA/Metro)

---

feeds/mta.info.dmfr.json

MTA New York

---

feeds/arlingtontransit.com.dmfr.json

https://www.arlingtontransit.com/riding-art/rider-tools/tools-for-developers/

Arlington Transit

---

feeds/mta.maryland.gov.dmfr.json

https://www.mta.maryland.gov/developer-resources

Maryland MTA

---

feeds/mountainline.com.dmfr.json
feeds/mountainline.usetransit.com.dmfr.json

two different Mountain Line agencies

---

feeds/sacrt.com.dmfr.json
feeds/trilliumtransit.com.dmfr.json

http://www.sacrt.com/schedules/gtfs.aspx

South County Transit Link

---

feeds/translink.com.au.dmfr.json

https://gtfsrt.api.translink.com.au/

Add GTFS-RT for Queensland, Australia

---

feeds/pigma.fr.dmfr.json

All infos are taken from GTFS' agency.txt file.

Add PIGMA, with aggregated Nouvelle Aquitaine french regional GTFS feed

---

feeds/bt4uclassic.org.dmfr.json

Blacksburg Transit

---

feeds/dipl.nt.gov.au.dmfr.json

Northern Territory, Australia

---

feeds/nationalrtap.org.dmfr.json
feeds/trilliumtransit.com.dmfr.json

received via email
related to #564

Fresno County Rural Transit Agency

---

feeds/martin.fl.us.dmfr.json

Martin County Public Transit

---

feeds/data.metropoletpm.fr.dmfr.json

Hello,
Here's a new network, Réseau Mistral, from the city of Toulon in France.
Have a good day !

Add Réseau Mistral

---

feeds/umich.edu.dmfr.json

University of Michigan

---

feeds/ridetransit.org.dmfr.json
feeds/transitland.github.com.dmfr.json

Charlotte Area Transit System

---

feeds/namtang.otp.go.th.dmfr.json

https://namtang.otp.go.th/opendata

Thailand, mostly Bangkok for now

---

feeds/stanrta.org.dmfr.json
feeds/trilliumtransit.com.dmfr.json

https://www.stanrta.org/431/GTFS-Information-Datasets

Stanislaus Regional Transit Authority (StanRTA)

---

feeds/catchacat.org.dmfr.json

https://www.catchacat.org/current-schedules/

Chatham Area Transit

---

feeds/matatransit.com.dmfr.json

https://www.matatransit.com/how-do-you-travel/route-schedules/gtfs-feed/

Memphis Area Transit Authority (MATA)

---

.github/workflows/update-gbfs.yml
.github/workflows/update-mds.yml
.github/workflows/validate.yml

https://github.com/interline-io/transitland-lib/releases/tag/v0.11.1

upgrade to latest version of transitland-lib

---

feeds/transmilenio.gov.co.dmfr.json

unstable url

---

feeds/onmetro.com.dmfr.json
feeds/s3.amazonaws.com.dmfr.json

Omaha Metro

---

feeds/transitland.github.com.dmfr.json
feeds/wrtaonline.com.dmfr.json

It seems they Also has Realtime:
https://myvalleystops.wrtaonline.com/infopoint/GTFS-Realtime.ashx?Type=TripUpdate
https://myvalleystops.wrtaonline.com/infopoint/GTFS-Realtime.ashx?Type=Alert
https://myvalleystops.wrtaonline.com/infopoint/GTFS-Realtime.ashx?Type=VehiclePosition

Western Reserve Transit Authority

---

feeds/parkcity.org.dmfr.json

from: https://www.parkcity.org/departments/transit-bus/gtfs

update unstable URL for Park City Transit 

---

feeds/trilliumtransit.com.dmfr.json

added Goose Creek Transit - Sheridan, WY

sheridan-wy-us

---

feeds/dati.piemonte.it.dmfr.json

update url's from:
- https://www.dati.piemonte.it/#/catalogodetail/regpie_ckan_ckan2_yucca_sdp_smartdatanet.it_ServizioProgrammatoDelTrasportoPubblicoRegionePiemonteAutobus_5186
- https://www.dati.piemonte.it/#/catalogodetail/regpie_ckan_ckan2_yucca_sdp_smartdatanet.it_ServizioProgrammatoDelTrasportoPubblicoRegionePiemonteTreniRegionali_5188

Update Piemonte Bus + Regional Train

---

feeds/sunline.org.dmfr.json

It seems they also have realtime feeds:
- https://infopoint.sunline.org/InfoPoint/GTFS-Realtime.ashx?Type=Alert
- https://infopoint.sunline.org/InfoPoint/GTFS-Realtime.ashx?Type=Tripupdate
- https://infopoint.sunline.org/InfoPoint/GTFS-Realtime.ashx?Type=VehiclePosition

update url for: SunLine(SunLine Transit Agency)

---

feeds/porto.digital.dmfr.json

Porto STCP

---

feeds/passio3.com.dmfr.json

Stevens Point, WI

---

feeds/dashbus.com.dmfr.json

Alexandria Transit Company (DASH)

---

feeds/circulatordashboard.dc.gov.dmfr.json
feeds/trilliumtransit.com.dmfr.json

update Trillium feeds

---

feeds/lacmta.github.com.dmfr.json
feeds/trilliumtransit.com.dmfr.json

from https://github.com/LACMTA/los-angeles-regional-gtfs

small cities around Los Angeles

---

feeds/trilliumtransit.com.dmfr.json
linktransit.com.dmfr.json

NOTE: I was having trouble editing https://github.com/transitland/transitland-atlas/pull/685 so restarted it in a new PR

Link Transit: static and RT feed

---

feeds/catchacat.org.dmfr.json

Source: https://www.catchacat.org/developer-resources/

update unstable url for: CAT - Chatham Area Transit

---

feeds/scgov.net.dmfr.json

updated from: https://scatmyride.tripsparkhost.com/gtfs/

update SCAT (Sarasota County Area Transit)

---

feeds/enture.org.dmfr.json

Until we have a more fully developed rate limit system for imports or fetches

Temporarily set manual_import for Ruter

---

feeds/rmwb.ca.dmfr.json

source: https://www.rmwb.ca/en/transit/transit.aspx#Advanced-Transit-Data-for-App-Developers

update: Regional Municipality of Wood Buffalo Transit

---

feeds/gtfs.calitp.org.dmfr.json

Cal-ITP flex feeds

---

feeds/nabsa.github.com.dmfr.json
feeds/ontarionorthland.ca.dmfr.json
feeds/openmobilityfoundation.github.com.dmfr.json
scripts/convert-gbfs-csv-to-dmfr.py
scripts/convert-mds-csv-to-dmfr.py

https://github.com/transitland/distributed-mobility-feed-registry/releases/tag/v0.4.1

update misc files to use DMFR v0.4.1

---

feeds/stm.info.dmfr.json

they make you make an account to find the endpoints, but then don't require a key nor explain how to use the key, so...

stm gtfs-rt

---

feeds/data.detroitmi.gov.dmfr.json
feeds/ivyryze.github.com.dmfr.json

Detroit People Mover

---

feeds/transmilenio.gov.co.dmfr.json

Update with the latest gtfs feed from jan 2023

Update with latest feed for bogota Colombia

---

feeds/gtfs.irail.be.dmfr.json

Updated the TEC data source, since it was was from a third-party and outdated, to an official source. Also changed the website URL to their new one.

updated TEC data

---

feeds/transportforireland.ie.dmfr.json

https://www.transportforireland.ie/transitData/PT_Data.html

Transport for Ireland

---

feeds/itinisere.fr.dmfr.json

https://transport.data.gouv.fr/datasets/reseau-cars-region-isere-38

Cars Région Isère

---

feeds/tshimada291.github.com.dmfr.json
scripts/convert-jp-list-csv-to-dmfr.py

as cataloged by https://github.com/tshimada291/gtfs-jp-list-datecheck

Japanese GTFS feeds

---

feeds/data.ptv.vic.gov.au.dmfr.json

https://data-exchange.vicroads.vic.gov.au/docs/services/vehicle-position-trip-update-opendata

PTV real-time feeds

---

feeds/zenbus.net.dmfr.json

https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-du-reseau-sitac-calais-gtfs-gtfs-rt/?locale=en

Calais Zenbus

---

feeds/citypa.ca.dmfr.json

https://www.citypa.ca/en/parking-streets-and-transportation/planning-your-route.aspx

Prince Albert Transit

---

feeds/hmrl.co.in.dmfr.json

https://data.telangana.gov.in/search/?theme=GTFS

Telangana state, India

---

feeds/transporlis.pt.dmfr.json

https://www.transporlis.pt/Default.aspx?tabid=314&codOp=41&language=pt-PT

Transporlis (Portugal)

---

feeds/dpmlj.cz.dmfr.json

Public feed of DPMLJ (found at https://www.dpmlj.cz/opendata)

add dpmlj.cz.dmfr.json

---

feeds/akronmetro.org.dmfr.json
feeds/yourmetrobus.org.dmfr.json

updated from: https://www.yourmetrobus.org/gtfs-and-shapefiles.aspx

update unstable url for: Akron Metro Regional Transit Authority

---

feeds/ridetransit.org.dmfr.json

javascript - jquery redirect ....

fix dl. URL for: CATS - Charlotte Area Transit System

---

feeds/eaglecounty.us.dmfr.json
feeds/trilliumtransit.com.dmfr.json

https://colorado-gtfs.trilliumtransit.com/

update eagle county

---

feeds/atlantaregional.com.dmfr.json
feeds/transloc.com.dmfr.json

Cherokee Area Transportation System

---

feeds/data.gouv.fr.dmfr.json
feeds/grandlyon.com.dmfr.json
feeds/itinisere.fr.dmfr.json
feeds/okina.fr.dmfr.json

more French feeds

---

feeds/at.govt.nz.dmfr.json

https://at.govt.nz/about-us/at-data-sources/general-transit-feed-specification/
https://dev-portal.at.govt.nz

Auckland Transport

---

feeds/gomcta.com.dmfr.json

Monroe County Transit Authority

---

feeds/oregon-gtfs.com.dmfr.json

set clatsopcounty-or-us gtfs to current

---

feeds/trilliumtransit.com.dmfr.json

re-activate, but retain `status=outdated` tag for tracking
related to #807
//cc @evantrillium

review Trillium feeds marked as historic

---

feeds/yourmetrobus.org.dmfr.json

update from: https://www.yourmetrobus.org/gtfs-and-shapefiles.aspx

update Akron Metro Regional Transit Authority URL

---

feeds/komunikacja.bialystok.pl.dmfr.json

I made up the Onestop IDs on the spot. Hopefully the json is ok :)

add GTFS Static feed for Białystok city in eastern Poland

---

feeds/ridecat.com.dmfr.json

update from: https://www.ridecat.com/gtfs/

update url for: Collier Area Transit

---

feeds/sardegnamobilita.it.dmfr.json

update from: https://atpsassari.it/muoversi-con-noi/open-data.html

update unstable url for: Azienda Trasporti Pubblici - Sassari

---

feeds/scgov.net.dmfr.json

source: https://scatmyride.tripsparkhost.com/gtfs/

update unstable url for: Sarasota County Area Transit

---

feeds/shuttle.txst.dmfr.json

source: https://www.shuttle.txst.edu/about/gtfs.html

update unstable url for: Bobcat Transit

---

feeds/kolejemalopolskie.com.pl.dmfr.json

Koleje Małopolskie

---

feeds/openmobilityfoundation.github.com.dmfr.json
scripts/convert-mds-csv-to-dmfr.py

A reactive fix to 3a9efdab664d75213c251f7420233b2ec590415f
A longer term fix would be #211

skip MDS feeds that don't have URLs provided

---

feeds/gotransit.com.dmfr.json

update source: https://www.gotransit.com/en/partner-with-us/software-developers

update URL for: GO Transit & UP Express

---

feeds/mountainline.com.dmfr.json

https://mountainline.com/about/data-portal/

Mountain Line

---

feeds/dcridestracker.com.dmfr.json

Adding Davidson County Transportation System (DC Rides) in Lexington, NC, to the Transitland Atlas. Please let me know if I'm missing anything, as this is my first time attempting this.

New Feed - DC Rides, Lexington, NC

---

feeds/motionbuscard.org.cy.dmfr.json

The links are found here: https://www.motionbuscard.org.cy/opendata

Add Cyprus bus operators

---

feeds/infra-hubup.fr.dmfr.json
feeds/zenbus.net.dmfr.json

https://transport.data.gouv.fr/datasets/donnees-theoriques-et-temps-reel

Tout'enbus

---

feeds/data.gouv.fr.dmfr.json
feeds/saint-etienne-metropole.fr.dmfr.json

Saint-Etienne

---

feeds/exo.quebec.dmfr.json

https://github.com/transitland/transitland-atlas/pull/904#discussion_r1281260202

fixing exo supersedes

---

feeds/zenbus.net.dmfr.json

Added three operators that are using Zenbus

MRC Montcalm, STC Pierre-De Saurel, MRC Haut-Saint-Laurent

---

feeds/middlesex.ca.dmfr.json

linked from https://www.middlesex.ca/service-information

add middlesex county

---

feeds/trilliumtransit.com.dmfr.json
feeds/tripshot.com.dmfr.json

Moved MVgo to Tripshot and updated URLs

Update MVgo GTFS and GTFS-RT

---

feeds/hub-mndot-prod.camsys-apps.com.dmfr.json

Minnesota DOT

---

feeds/mst.org.dmfr.json

https://mst.org/about-mst/developer-resources/

Monterey-Salinas Transit

---

feeds/datatools-nysdot.dmfr.json
feeds/gobroomecounty.com.dmfr.json
feeds/passio3.com.dmfr.json
feeds/transitland.github.com.dmfr.json

```sh
http https://s3.amazonaws.com/datatools-511ny/public/index.html | pup 'a attr{href}' | pbcopy
```

update New York state feeds

---

feeds/circulatordashboard.dc.gov.dmfr.json

Pulled from their developer resources: https://dccirculator.com/developer-resources/

update dc circulator url

---

feeds/nabsa.github.com.dmfr.json
scripts/convert-gbfs-csv-to-dmfr.py

pending https://github.com/MobilityData/gbfs/pull/550

fix an invalid GBFS feed auto-discovery URL

---

feeds/mvta.com.dmfr.json

Minnesota Valley Transit Authority

---

feeds/nabsa.github.com.dmfr.json
scripts/convert-gbfs-csv-to-dmfr.py

now that https://github.com/MobilityData/gbfs/pull/550 has been merged

sync GBFS from systems.csv again

---

feeds/nationalrtap.org.dmfr.json
feeds/transitland.github.com.dmfr.json

Stark Area Regional Transit Authority (SARTA)

---

feeds/cdta.org.dmfr.json
feeds/datatools-nysdot.dmfr.json

greater glens falls transit has been merged into the cdta

remove greater glens falls transit

---

feeds/stpbrindisi.it.dmfr.json

https://www.stpbrindisi.it/index.php/linee-e-orari/open-data-esercizio

STP-Brindisi

---

feeds/transitland.github.com.dmfr.json

Saginaw STARS

---

feeds/cityofwinona.com.dmfr.json

Winona (Minnesota)

---

scripts/validate-feeds.py

To catch some of the improper Onestop IDs identified in https://github.com/transitland/transitland-atlas/pull/1041

improve validation of Onestop IDs

---

feeds/optne.com.dmfr.json

linked towards bottom of https://www.optne.com/empty-page

open plains transit

---

feeds/drummondville.ca.dmfr.json
feeds/sttr.qc.ca.dmfr.json

Hello!
Here is Trois-Rivières and Drummondville.
Trois-Rivières has realtime data, I'll check with them if it's public.
Thanks!

Added Trois-Rivières and Drummondville

---

.github/workflows/update-gbfs.yml

try to have GBFS update workflow open a PR

---

.github/workflows/update-mds.yml

When GitHub Actions updates MDS, it will now open a PR

---

feeds/thello.axelor.com.dmfr.json

Add GTFS and GTFS-RT feeds from Trenitalia France.

Add Trenitalia France (Thello) feeds.

---

feeds/arcgis.com.dmfr.json
feeds/wstransit.com.dmfr.json

Created new file feeds/wstransit.com.dmfr.json for Winston-Salem Transit Authority in Winston-Salem, NC

New Feeds - Winston-Salem Transit Authority, Salisbury Transit & Gastonia Transit

---

feeds/cityofglendora.org.dmfr.json
feeds/cityofinglewood.org.dmfr.json
feeds/cityofsouthgate.org.dmfr.json
feeds/lacmta.github.com.dmfr.json
feeds/passio3.com.dmfr.json
feeds/syncromatics.com.dmfr.json

Thanks to https://github.com/LACMTA/los-angeles-regional-gtfs/pull/188

Los Angeles area

---

feeds/cityofspartanburg.org.dmfr.json

https://www.cityofspartanburg.org/447/GTFS-Data

Spartanburg (South Carolina)

---

feeds/scgov.net.dmfr.json

Breeze (Sarasota, FL)

---

feeds/data.gov.my.dmfr.json

Added feed for Malaysia's public transport operators from https://developer.data.gov.my (KTM Berhad, Causeway Link myBas, Prasarana Rapid Bus and Rapid Rail) to `feeds/data.gov.my.dmfr.json`

New feed - Malaysian public transit (KTMB, myBas, Rapid Rail, Rapid Bus)

---

feeds/translink.ca.dmfr.json

proposed in https://github.com/transitland/transitland-atlas/pull/1114

new TransLink (Vancouver) RT endpoints

---

feeds/goraleigh.org.dmfr.json

Correcting `static_current` in an effort to pull new system route changes. Also adding license attribution and shifting `operators` outside of `feeds`.

Update - GoRaleigh (Raleigh, NC, USA)

---

feeds/gotriangle.org.dmfr.json
feeds/trilliumtransit.com.dmfr.json

Created new file for GoTriangle (feeds\gotriangle.org.dmfr.json) and added realtime feeds (source: [GoTriangle Developer Resources](https://gotriangle.org/developer-resources)).

Update - GoTriangle (Durham, NC, USA)

---

feeds/fairfaxva.gov.dmfr.json

Fairfax (city) Virginia

---

feeds/mychtransit.org.dmfr.json
feeds/syncromatics.com.dmfr.json
feeds/trilliumtransit.com.dmfr.json

Created new file for Chapel Hill Transit (feeds\mychtransit.org.dmfr.json) and consolidated static and realtime feeds there.

Update - Chapel Hill Transit (Chapel Hill, NC, USA)

---

feeds/passio3.com.dmfr.json
feeds/transloc.com.dmfr.json

Rochester Institute of Technology

---

.github/workflows/format.yaml

an example of the failure:
https://github.com/transitland/transitland-atlas/actions/runs/9711393064/job/26821608522?pr=1163

try to fix GH Actions workflow that automatically formats DMFR files in PRs

---

feeds/sarkshippinggtfs.fly.dev.json

This adds Sark Shipping passenger ferry timetables - https://www.sarkshipping.gg

feat: add Sark Shipping

---

feeds/passio3.com.dmfr.json

Rochester Institute of Technology real-time

---

feeds/daytrip.com.dmfr.json

We are Daytrip Shuttle, and we operate multiple shuttle routes around the world.
We would like to add first 2 feeds in Italy and Portugal in Transit.Land and more feeds will be coming.

Add feed file for daytrip gtfs feeds

---

feeds/s3.amazonaws.com.dmfr.json
feeds/transloc.com.dmfr.json

Gary Public Transportation Corporation

---

feeds/broward.org.dmfr.json

Broward County Transit

---

feeds/massdot.state.ma.us.dmfr.json
feeds/trilliumtransit.com.dmfr.json

MassDOT commuter buses

---

feeds/jptransit.org.dmfr.json
feeds/transitland.github.com.dmfr.json

Jefferson Parish Transit

---

feeds/mobilityeqity.github.com.dmfr.json
feeds/transitland.github.com.dmfr.json

https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/138

Shore Transit (Maryland)

---

feeds/citrusbocc.com.dmfr.json
feeds/trilliumtransit.com.dmfr.json

Citrus County (FL)

---

feeds/lillemetropole.fr.dmfr.json

Ilevia (Lille Metropole)

---

feeds/bctracker.ca.dmfr.json

West Coast Trail Express (British Columbia)

---

feeds/oregon-gtfs.com.dmfr.json

South Lane Wheels no longer operates fixed-route service

---

feeds/jptransit.org.dmfr.json

JP Transit

---

feeds/transitland.github.com.dmfr.json

received via email
https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/140

Gaston ACCESS

---

feeds/metrolinx.tmix.se.dmfr.json
feeds/trilliumtransit.com.dmfr.json

closes https://github.com/transitland/transitland-atlas/pull/1266

Bow Valley

---

feeds/cityway.fr.dmfr.json
feeds/mecatran.com.dmfr.json

https://www.data.gouv.fr/en/datasets/5b3b3de988ee38708ada1789/?resources=all#/resources

Pays d'Aix mobilité

---

feeds/daytrip.com.dmfr.json

related to https://github.com/transitland/transitland-atlas/pull/1193

another Daytrip Shuttle feed

---

feeds/wienerlinien.at.dmfr.json

https://www.data.gv.at/katalog/en/dataset/wiener-linien-fahrplandaten-gtfs-wien#resources

Wiener Linien (Vienna, Austria)

---

feeds/datatools-nysdot.dmfr.json
feeds/mitsbus.org.dmfr.json
feeds/nationalrtap.org.dmfr.json
feeds/oregon-gtfs.com.dmfr.json
feeds/transitland.github.com.dmfr.json
feeds/trilliumtransit.com.dmfr.json

Tag feeds archived:
- MRTA
- Hernando Express
- Eugene-to-Bend
- TappanZee Express
Tag feeds outdated:
- MITS Bus
- City of Sierra Vista
- Greenway

Archived and Outdated Tags (multiple)

---

feeds/freedom-transit.org.dmfr.json
feeds/freedom.rideralerts.com.dmfr.json

They also use mySTOP (Avail Technologies) I think it would be better to use GTFS realtime then static.

Use Avail for GTFS & GTFS Realtime Data (Freedom Transit)

---

feeds/datatools-nysdot.dmfr.json
feeds/rgrta.com.dmfr.json
scripts/ntd-gtfs-weblinks/2023-gtfs-weblinks.dmfr.json

unclear which of these feeds are still active; we may have to revisit to cull some in the future

Rochester (New York) area

---

feeds/bctransit.com.dmfr.json

https://www.bctransit.com/open-data/

BC Transit

---

feeds/data.ptv.vic.gov.au.dmfr.json

https://data.ptv.vic.gov.au/downloads/GTFSReleaseNotes.pdf

review Public Transport Victoria feeds

---

feeds/porto.digital.dmfr.json

Change STCP GTFS URL to 2024 version

---

feeds/amtrak.com.dmfr.json
feeds/mountaintransit.org.dmfr.json
feeds/trilliumtransit.com.dmfr.json

- Add 19 new feeds
- Update 2 feed URLs

Add 21 new feeds

---

feeds/durangogov.org.dmfr.json
feeds/trilliumtransit.com.dmfr.json

- Add discovergoodwill-co-us
- Add dolorescounty-co-us
- Add durangotransit-co-us-flex

Add 3 Trillium feeds

---

feeds/emap.mesacounty.us.dmfr.json
feeds/metlink.org.nz.dmfr.json
feeds/mjcaction.com.dmfr.json
feeds/trilliumtransit.com.dmfr.json

Add batch of Trillium feeds, including flex feeds for existing feeds.
- eastbywest-nz
- eastside-wa-us
- eccog-co-us
- elpaso-co-us
- grandvalleytransit-flex
- gunnisonvalleyrta-co-us-flex

Add 6 agencies

---

feeds/scgov.net.dmfr.json

Breeze Transit

---

feeds/scgov.net.dmfr.json

Breeze Transit (Sarasota County, FL)

---

feeds/cimmt.pt.dmfr.json

This is the official feed for Médio Tejo.
We don't have a better (non-Google Drive) URL at hand.  This is the very same URL that sources Google Maps.
I do have the authorization to publish it under this license.
Cheers,
Cláudio

Médio Tejo (Portugal)

---

feeds/shoretransit.org.dmfr.json
feeds/transitland.github.com.dmfr.json

Shore Transit

---

feeds/nationalrtap.org.dmfr.json

Sierra Vista Transit

---

feeds/nationalrtap.org.dmfr.json
feeds/s3.amazonaws.com.dmfr.json
feeds/swrpc.org.dmfr.json
feeds/transitland.github.com.dmfr.json
feeds/tricountytransit.org.dmfr.json
feeds/westbusservice.com.dmfr.json
feeds/wmtsbus.org.dmfr.json
scripts/ntd-gtfs-weblinks/2023-gtfs-weblinks.dmfr.json

various new england feeds, most from ntd

new england feeds

---

.github/workflows/format.yaml

wasn't working on https://github.com/transitland/transitland-atlas/pull/1432

fix `git diff` output used by format.yaml

---

.github/workflows/format.yaml

try format.yaml again with multiline GH output

---

.github/workflows/format.yaml

try format.yaml again

---

feeds/oregon-gtfs.com.dmfr.json

closes https://github.com/transitland/transitland-atlas/pull/1443

Updating sctd fetch URL to https

---

feeds/arcgis.com.dmfr.json
feeds/avecbili.ca.dmfr.json
feeds/contenu.sto.ca.dmfr.json
feeds/fredericton.tmix.se.dmfr.json
feeds/hinton.ca.dmfr.json
feeds/ticpoi.com.dmfr.json

based on review of https://www150.statcan.gc.ca/n1/pub/23-26-0003/232600032025001-eng.htm

assorted Canadian feeds

---

feeds/511.org.dmfr.json

closes https://github.com/transitland/transitland-atlas/issues/1438

switch SamTrans feed to MTC 511.org version

---

feeds/trilliumtransit.com.dmfr.json

Modified Kimball transit

---

feeds/oregon-gtfs.com.dmfr.json
feeds/passio3.com.dmfr.json
feeds/tu-vp.goswift.ly.dmfr.json

Cascades East Transit

---

feeds/nap.transportes.gob.es.dmfr.json

fixing Spanish Onestop IDs

---

feeds/dashbus.com.dmfr.json

Alexandria DASH

---

feeds/metrotas.com.au.dmfr.json

Tasmania, Australia

---

feeds/centro.org.dmfr.json
feeds/datatools-nysdot.dmfr.json

received via email:
https://www.centro.org/docs/default-source/press-releases/centro-begins-bus-service-in-cortland-county.pdf?sfvrsn=307efc6_1

Centro replacing Cortland Transit

---

external-data-for-reference/ntd-gtfs-weblinks/2023-gtfs-weblinks.dmfr.json
feeds/trilliumtransit.com.dmfr.json

RTC Washoe

---

feeds/peatus.ee.dmfr.json
feeds/stops.lt.dmfr.json

License sources: 
https://data.europa.eu/data/datasets/https-data-gov-lt-datasets-1929-?locale=de
https://avaandmed.eesti.ee/datasets/tartu-linna-uhistranspordi-peatuste-numbrid-ja-nimekiri-asukohad-ja-soiduplaanid

add licenses for feeds

---

feeds/blueskylimovail.com.dmfr.json

This pull request adds the GTFS schedule feed for Blue Sky Limo LLC, a private shuttle service operating fixed-route airport transfers between DEN, EGE, and Colorado mountain destinations.
Feed URL: https://blueskylimovail.com/blueskylimo_gtfs.zip  
License: CC BY 4.0  
Operator: Blue Sky Limo LLC (based in Vail, CO)

Add Blue Sky Limo GTFS feed

---

feeds/pinpointavl.com.dmfr.json

https://www.pinpointavl.com/gtfs

Santa Cruz feeds

---

feeds/transitland.github.com.dmfr.json

https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/151

Chillicothe, OH

---

feeds/gtfs.calitp.org.dmfr.json
feeds/tripshot.com.dmfr.json

according to https://www.smoothinc.org/flyer-express.php

Guadalupe Flyer is now operated by Santa Maria Regional Transit

---

feeds/nationalrtap.org.dmfr.json

Rapid City, SD

---

feeds/transitland.github.com.dmfr.json

https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/154

two airport people movers

---

feeds/data.gouv.fr.dmfr.json
feeds/data.gov.rs.dmfr.json

move 2 France feed out from file: data.gov.rs.dmfr.json to the correct file: data.gouv.fr.dmfr.json and update one of the feeds

Urbain tungt

---

feeds/opentransportdata.swiss.dmfr.json
feeds/sncf.com.dmfr.json

closes https://github.com/transitland/transitland-atlas/issues/1682

consolidate SNCF feeds

---

feeds/nationalrtap.org.dmfr.json
feeds/trilliumtransit.com.dmfr.json

Butte-Silver Bow

---

feeds/mountaintransit.org.dmfr.json

Mountain Transit

---

scripts/convert-gbfs-csv-to-dmfr.py

to fix problem in https://github.com/transitland/transitland-atlas/pull/1751

remove all punctuation from GBFS Onestop IDs

---

feeds/github.com.dmfr.json

This feed was generated somewhat manually in conjunction with the folks at Columbia County

Add Columbia County Public Transportation

---

external-data-for-reference/japan/convert-tshimada291-list-csv-to-dmfr.py

Correcting output path to a path where a file exists

Fixing japan workflow not running 
