transitland/transitland-atlas

- feeds/github.com.dmfr.json
https://github.com/septadev/GTFS/releases/tag/v202003220
> latest SEPTA feed versions

- feeds/data.trilliumtransit.com.dmfr.json
static_current is incorrect on website, but trinity isn't in the other dmfr.json files
> added f-9r0-trinity~ca~us 

- feeds/nvbw.de.dmfr.json
extracted from https://www.nvbw.de/open-data/fahrplandaten/fahrplandaten-mit-liniennetz using
```
http https://www.nvbw.de/open-data/fahrplandaten/fahrplandaten-mit-liniennetz | pup 'a attr{href}' | rg '.zip'
```
closes #118
> Baden-Württemberg feeds

- feeds/transitland.github.com.dmfr.json
related to https://github.com/transitland/gtfs-archives-not-hosted-elsewhere/pull/74
> Stark Area Regional Transit Authority (SARTA)

- feeds/api.goswift.ly.dmfr.json
GTFS-realtime feeds are not showing up in Transitland V2 pages:
- https://www.transit.land/operators/o-9xj5s-viamobilityservices
- https://www.transit.land/operators/o-dqcq-regionaltransportationagencyofcentralmaryland
I believe the issue is because `feed_namespace_id` is not set. `associated_feeds` is set, but appears insufficient.
This PR sets those values for the feeds
> Add feed_namespace_ids to Swiftly feeds

- operators/o-dr4-septa.json
one feed does have `agency_id` (the other does not)
> SEPTA operator

- feeds/tcatbus.com.dmfr.json
TCAT has a realtime feed defined but it isn't correctly associated with it on the website. I followed the BART DMFR JSON as a guide to attempt to fix this.
> Associate TCAT realtime feed with operator

- feeds/dartfirststate.com.dmfr.json
DART has changed the URL where GTFS can be found.
> Update URL for dartfirststate

- feeds/mobilityeqity.github.com.dmfr.json
See the link on this page: https://www.princegeorgescountymd.gov/1122/Routes-Schedules
Unfortunately this URL will eventually change again, and also there are some inadequacies in the stop_times, at least as far as OpenTripPlanner is concerned.
> Update URL for f-dqc-thebusofprincegeorgescounty

- feeds/mkuran.pl.dmfr.json
the feed contains an `attributions.txt` file
> ZTM Warszawa requires OSM attribution

- feeds/opendata.straeto.is.dmfr.json
Source data and licence doc available from <https://www.straeto.is/is/um-straeto/leidakerfi/opin-rafraen-gogn>.
Strætó is the publicly-owned company that operates buses within Reykjavík and its surrounding towns, along with a few other routes around the country.
> Add GTFS feed for Icelandic bus company Strætó

- feeds/511.org.dmfr.json
will be marked for manual import, until we are ready to excluse other agency-level feeds from global search
> SF Bay Area Regional GTFS Feed

- feeds/github.com.dmfr.json
I run the GTFS feed for RIOC - we store the feed at the National RTAP link above. This is the link referenced by Google et. al.
The one currently in there appears to be wrong and has not been updated in a number of years.
> Link to real (and updated) GTFS for RIOC

- feeds/nationalrtap.org.dmfr.json
One of BATA's transportation planners provided this slightly modified link.
> Update the URL for BATA_GTFS.zip

- feeds/zsr.sk.dmfr.json
ZSR and ZSSK are under one corporate umbrella, ZSR regulates Railway tracks in Slovakia, whilst ZSSK is major Rail Service Provider here. Taken from Slovakia Open Data Portal (https://data.gov.sk/dataset/https-www-zsr-sk-files-pre-cestujucich-cestovny-poriadok-gtfs-gtfs-zip)
> Adds `ZSSK` via ZSR

- feeds/trilliumtransit.com.dmfr.json
uses https://github.com/interline-io/transitland-lib/pull/181
to make it easier to detect the differences in #465
> format the Trillium file using the new `transitland dmfr format --save` command

- feeds/oregon-gtfs.com.dmfr.json
I wonder why this wasn't caught in the validation of #441
> fix `static_historical` URLs in oregon-gtfs DMFR

- feeds/data.toulouse-metropole.fr.dmfr.json
Hello,
Tisséo released a new v2 set and deprecated the v1 set.
I updated the URL with the new dataset.
Have a good day !
> Update Tisséo to the new v2 dataset

- feeds/data.lpp.si.dmfr.json
Looks like the feed URL for *Ljubljanski Potniški Promet* (Ljubljana, Slovenia) has been down for a few years now. 
I've updated it to the correct URL.
> Updated LPP to use the new GTFS URL

- feeds/norta.com.dmfr.json
No, "OpnesourceData" is not a typo. 
Access to feed requires creating an account and agreeing to their terms, which can be a bit finicky with their jank website, after which they email you a direct link with your key already appended to the URL.  Additionally, RT feeds are available, if you're willing to jump through a few more hoops, at the same URL.
> Update NORTA static feed

- feeds/navarra.es.dmfr.json
from: https://datosabiertos.navarra.es/es/dataset/transporte-p-blico-interurbano-regular-de-viajeros-en-autob-s
> udpate Navarra Public Transport

- feeds/gohrt.com.dmfr.json
unrelated to this particular pull but when the file was renamed in a prior pull, it appears to have broken the github link on the operator [page](https://www.transit.land/operators/o-dq9-hamptonroadstransithrt), where it still references the old file name
> add hrt gtfs-rt

- feeds/connexionz.net.dmfr.json
they claim on the developer page that /data/gtfs.zip works... but it clearly doesn't, so changed it out for the other link provided
> fix KART url

- feeds/stanrta.org.dmfr.json
- feeds/trilliumtransit.com.dmfr.json
ceres and stanislaus have been merged (along with others) into one agency, so removing duplicated routes
> remove ceres area transit and stanislaus regional transit

- feeds/itransitnw.com.dmfr.json
- feeds/mjcaction.com.dmfr.json
itransitnw shows routes for the whole region... but the standard connexionz export only gives gtfs for valley transit
> update valley transit, wa

- feeds/data.agglo-royan.fr.dmfr.json
update source: https://transport.data.gouv.fr/datasets/donnees-gtfs-du-reseau-de-transport-public-cara-bus
> update: Transdev Royan Atlantique

- feeds/opendata.vlci.valencia.es.dmfr.json
updated from: https://opendata.vlci.valencia.es/dataset/google-transit-lines-stops-bus-schedules
> Update url for EMT Valencia

- feeds/norwalktransit.com.dmfr.json
updated from: https://norwalktransit.com/public-information/
> update (unstable) url for: Norwalk Transit District

- README.md
Before this PR, clicking one of the links in the readme pointed to a `#onestopids` that doesn't exist. The ID is actually `#onestop-ids` (https://github.com/transitland/transitland-atlas#onestop-ids)
> fix readme broken header id link

- feeds/dart.org.dmfr.json
this license is for the wrong DART, (Des Moines Area Regional Transit Authority)
> remove wrong dart license

- feeds/zenbus.net.dmfr.json
update from: https://transport.data.gouv.fr/datasets/horaires-theoriques-et-temps-reel-de-la-station-de-ski-les-saisies-gtfs-gtfs-rt
(Unfortunately the feed is expired at the moment)
> fix typo in url for: Navettes Les Saisies

- feeds/gocarta.org.dmfr.json
update unstable url for: CARTA Chattanooga Area Regional Transportation Authority
update source: https://www.gocarta.org/about/developers-center/
> update unstable url for: CARTA

- feeds/trilliumtransit.com.dmfr.json
it seems from here: https://data.trilliumtransit.com/gtfs/tricap-mn-us/
that the tricap-mn-us.zip file does not exists there only the: tricap-mn-us--flex-v2.zip file
> fix url for: f-tricap~mn~us

- feeds/porolakka.github.com.dmfr.json
Hello, I am a member of an experimental project that aims to provide visually impaired individuals with the timetable of the free shuttle buses at Haneda Airport in Japan.
* This Pull Request adds a link to the GTFS (ZIP file) that includes the timetable for the shuttle bus of Haneda Airport.
* The corresponding GTFS file was created using a dedicated tool and has undergone a basic check.
* To make the json file,  I referenced your README.md and some linked documentation.
* Since this is my first pull request, please let me know if there are any errors in the file or if there are any mistakes in the way it was added.
> add feed of HanedaINL Free Shuttle Bus

- feeds/carrismetropolitana.github.com.dmfr.json
- feeds/transporlis.pt.dmfr.json
Added the joint Carris Metropolitana area feed. Removed per-area (a2,a3,a4) Carris Metropolitana feeds. Removed old Lisbon metro area bus operators that were replaced by Carris Metropolitana. Removed discontinued Carristur airport bus brand.
> Updates to Lisbon, Portugal feeds

- feeds/bartabus.com.dmfr.json
- feeds/redrosetransit.com.dmfr.json
- feeds/transitland.github.com.dmfr.json
both github files are nearly two years out of date, and apparently the two agencies have finally made their GTFS export available
> update barta and rrta

- feeds/coruna.es.dmfr.json
https://datos.coruna.gal/dataset/autobuses-urbanos
> Compañía de Tranvías de A Coruña

- feeds/exo.quebec.dmfr.json
This PR removes Le Richelain and Roussillon and combines them into one operator (effective as of July 31st). Also, GTFS-RT feeds for every sector have been added.
> exo - Merging of two sectors and clean up

- feeds/carris.pt.dmfr.json
- feeds/carrismetropolitana.github.com.dmfr.json
Firstly, CARRIS != Carris Metropolitana.
Lisbon (District) is composed of multiple municipalities. CARRIS only operates on one of those municipalities: Lisbon (Municipality) while Carris Metropolitana operates on some of the others (which includes Lisbon (Municipality), but limitedly because CARRIS is on an exclusivity agreement for that part of the district).
The first historical feed url for Carris Metropolitana was actually an old source for CARRIS feeds.
The url to the license I included applies to the old data that was provided via an intermediate, Transporlis.
I imagine the same license applies to the current data. CARRIS moved towards sharing the GTFS feed directly from their systems and do not provide any license info.
Thanks!
> Add CARRIS and change Carris Metropolitana history

- feeds/lacmta.gitlab.com.dmfr.json
- feeds/massdot.state.ma.us.dmfr.json
- feeds/scgov.net.dmfr.json
- https for some feeds
- update name of Breeze Transit (formerly Sarasota County Area Transit)
- fix LA Metro alerts feed spec - reported on https://github.com/transitland/transitland-atlas/pull/933
> Assorted small updates

- feeds/ftis.org.dmfr.json
- feeds/ridecitrus.com.dmfr.json
per https://ridecitrus.com/routes/east-county-routes/, there are feeds from both avail (similar to ftis feed) and passio, though even now there seem to be some missing routes
> update citrus connection

- feeds/schedules.jtafla.com.dmfr.json
New source for Jacksonville Transport Authority. Old one doesn't work.
> Jacksonville Transport Authority

- feeds/brampton.ca.dmfr.json
The old URL for Brampton Transit wasn't working. I found the current webpage that GTFS Schedule feeds can be downloaded from.
> New source for Brampton Transit

- feeds/buswhere.com.dmfr.json
- feeds/data.omnimodal.io.dmfr.json
This PR updates the I-RIDE Trolley feed to be up to date.
The I-RIDE Trolley in the I-Drive Business Improvement District has switched from OmniModal (which is now redirecting to spam/ads) to BusWhere. This PR changes the I-RIDE Trolley to use the new vendor.
Data feed was sourced by staff at the I-Drive Business Improvement District. URL is `https://buswhere.com/iridetrolley/gtfs/schedule`.
The remaining OmniModal service, the [Sanford Community Redevelopment Agency trolley service](https://sanfordfl.gov/residents/free-trolley-service/), uses TSOMobile. I do not have their GTFS feed available; more research (i.e., contacting them) is necessary and is out of scope for this PR.
> Updated feed for I-RIDE Trolley.

- feeds/mobilites-m.fr.dmfr.json
* License for all the mobilites-m.fr feeds is documented at https://data.mobilites-m.fr/donnees
* There's a missing feed for cars
> Add France Isère (38) cars

- feeds/kolejedolnoslaskie.pl.dmfr.json
- feeds/mkuran.pl.dmfr.json
This PR:
1. Removes the unofficial GTFS feed of the Polish regional rail operator, Koleje Dolnośląskie (eng. Lower Silesia Railways) provided by @MKuranowski
2. Replaces it with the official feed from the operator's website: https://kolejedolnoslaskie.pl/rozklady-gtfs/
There are some caveats:
1. The feed needs a username and password to access. The credentials are given in plaintext in the URL that I've shown above (CTRL+f "login" on that page, no need to know Polish). I'm thinking putting the password in public defeats the purpose of having a password in the first place. I assume that transitland doesn't handle storing secrets used to access the .zips, right? The "Authorization" key in the dmfr json is purely informational, right?
2. I'm not sure if I should be removing the …
> Use official GTFS feed of Polish regional rail operator - Koleje Dolnośląskie

- feeds/carrismetropolitana.github.com.dmfr.json
This change adds the realtime feeds from Carris Metropolitana, and additional metadata (WikiData, short name, twitter).
> Update carrismetropolitana with RT feeds

- feeds/carris.pt.dmfr.json
- feeds/carrismetropolitana.github.com.dmfr.json
Referring to a different reporter's explanation in: https://github.com/transitland/transitland-atlas/pull/926#issue-1858236772
These are two different operators.
Currently, there are two onestop ids in the website:
o-eyc-carrismetropolitana
o-eyck-carris
The latter currently contains both Carris Metropolitana and Carris, which is wrong.
In this update, I've aligned the onestop IDs present on the website with the onestop IDs in the files, by associating:
o-eyc-carrismetropolitana -> Carris Metropolitana
o-eyck-carris -> Carris
Additionally, I've been told that Carris Metropolitana is now suggesting all users to refer to the API for all feeds, not just RT ones, so I put the new URL in.
> Disambiguate Carris and Carris Metropolitana

- feeds/comboiosdeportugal.pt.dmfr.json
- feeds/transporlis.pt.dmfr.json
Hi,
This adds the new Comboios de Portugal feed that is now provided directly by them instead of being served via Transporlis.
I also removed the feed from the Transporlis DMFR file.
Thanks! 🚀
> Add new Comboios de Portugal (CP) feed

- feeds/passio3.com.dmfr.json
- feeds/wstransit.com.dmfr.json
Adding feeds for UNC Charlotte and Elon University (per their websites, both are open to the community/visitors).
Adding realtime feeds for Jacksonville Transit in Jacksonville, NC.
Changing `short_name` for Concord Kannapolis Area Transit to "Rider" ([source](https://www.transit.dot.gov/sites/fta.dot.gov/files/transit_agency_profile_doc/2022/40167.pdf)).
Adding `short_name` attribute for NCSU Wolfline.
Removing inaccurate `Wikidata Entity ID` attribute from Winston-Salem Transit Authority (no Wikidata article found).
> Update - Passio Feeds (UNCC, Elon, Jacksonville)

- feeds/gocary.org.dmfr.json
Adding realtime feeds for GoCary. Also, removing "Cary Transit" name, as this is no longer their official name ([source](https://www.transit.dot.gov/sites/fta.dot.gov/files/transit_agency_profile_doc/2022/40143.pdf)).
> Update - GoCary (Cary, NC, USA)

- feeds/alerts.goswift.ly.dmfr.json
- feeds/trilliumtransit.com.dmfr.json
- feeds/tu-vp.goswift.ly.dmfr.json
thanks to https://github.com/transitland/transitland-atlas/pull/1161
> City of Avalon (California) no longer operates fixed-route transit

- feeds/dati.piemonte.it.dmfr.json
- feeds/dati.toscana.it.dmfr.json
This PR replaces the existing data for Tuscany with data taken from [OpenToscana's official feed](https://dati.toscana.it/dataset/rt-oraritb.xml).
Major changes:
* A number of bus companies in the previous file no longer exist and have been removed,
* All Tuscan bus routes are now covered,
* URLs are now all https,
* Geohashes are calculated to be as precise as possible while covering all stop locations.
The file is generated via this repo: https://github.com/joeyates/transitland-dati-toscana-it
> Regenerate Toscana dati from feed

- feeds/mvv-muenchen.de.dmfr.json
This fixes the MVVs URL being a 404.
This will need to be updated semi-regularly, to their new arbitrairy timestamp :sigh:
A bit older, but with shapes data exists here:
https://www.govdata.de/suche/daten/soll-fahrplandaten-mvv
Sadly, this is not listed on their website
=> idk what the timestamp is for the ones with shapes
> Update the mvv's url

- .github/workflows/update-jp.yaml
- feeds/tshimada291.github.com.dmfr.json
- scripts/convert-jp-list-csv-to-dmfr.py
new script to handle the format of https://github.com/tshimada291/gtfs-jp-list-datecheck/blob/main/GTFS_fixedURL_LastModified.csv
related to https://github.com/transitland/transitland-atlas/pull/880 and https://github.com/tshimada291/gtfs-jp-list-datecheck/issues/1
> fix automatic updates of Japanese feed list

- feeds/ridewsta.com.dmfr.json
- scripts/ntd-gtfs-weblinks/2023-gtfs-weblinks.dmfr.json
WSTA in Winston-Salem, NC, has finally published a GTFS permalink on their website. Updating `static_current` to the new permalink, and renaming the DMFR to match the new URL.
> Update Feed - Winston-Salem Transit Authority

- feeds/toronto.ca.dmfr.json
This seems to trickle through all the way to https://www.transit.land/operators/o-dpz8-ttc
> Fix spelling mistake in Toronto Transit Commission

- feeds/opendata.rnv-online.de.dmfr.json
See https://www.opendata-oepnv.de//ht/de/organisation/verkehrsunternehmen/rnv/openrnv/datensaetze?tx_vrrkit_view%5Bdataset_name%5D=soll-fahrplandaten-rnv&tx_vrrkit_view%5Baction%5D=details&tx_vrrkit_view%5Bcontroller%5D=View
> Update static gtfs feed link of Rhein-Neckar-Verkehr GmbH

- feeds/hamilton.ca.dmfr.json
Since the city of Hamilton updates its feed 4 times a year, I left the old URL as is.
> Hamilton city feed url update

- feeds/api.resrobot.se.dmfr.json
There is no authorization needed for the trafiklab feed
> fix: authorization removed from trafiklab feed

- feeds/opendata.transport.nsw.gov.au.dmfr.json
> fix: updated authorization info_url in opendata.transport.nsw.gov.au feed

- feeds/kolejedolnoslaskie.pl.dmfr.json
I requested for GTFS creds for KD in https://github.com/transitland/transitland-atlas/issues/1034 so now I'm on their mailing list.
I' got an e-mail saying that the /vehicles endpoint provided GTFS-RT VehiclePositions, but now they have a /feed endpoint where they provide both VehiclePositions and TripUpdates
They explicitly ask to *switch* from /vehicles to /feed
> Add realtime_trip_updates for kolejedolnoslaskie

- feeds/trilliumtransit.com.dmfr.json
had been previously deprecated by Trillium staff, but is now maintained again
> Prince George's County

- .github/workflows/validate.yaml
otherwise it will just be validating whatever is in main branch, as it did for https://github.com/transitland/transitland-atlas/pull/1427
> validate.yaml needs to check out the PR contents

- feeds/datatools-nysdot.dmfr.json
- feeds/gtfs.calitp.org.dmfr.json
- feeds/nationalrtap.org.dmfr.json
- feeds/oregon-gtfs.com.dmfr.json
- feeds/ridetransfort.com.dmfr.json
- feeds/s3.amazonaws.com.dmfr.json
- feeds/transitland.github.com.dmfr.json
- feeds/trilliumtransit.com.dmfr.json
- feeds/tularecog.org.dmfr.json
Add:
- f-miamigardens\~fl\~us
- f-mountainexpress\~co\~us\~flex
- f-mountainfamilycenter\~co\~us\~flex
- f-nisqually\~wa\~us
- f-nsn\~nz
- f-ocpt\~nc\~us
- f-omnibus\~co\~us\~flex
- f-paratransitservices\~wa\~us\~flex
- f-prowerscounty\~co\~us\~flex
- f-psesd\~wa\~us\~flex
- f-rccoa\~co\~us\~flex
- f-scania\~se
- f-sccog\~co\~us\~flex
- f-silverkey\~co\~us\~flex
- f-soundgenerations\~wa\~us\~flex
- f-southwestrides\~co\~us\~flex
- f-squaxinisland\~wa\~us
- f-srda\~co\~us\~flex
- f-transfort\~co\~us\~flex
- f-trc\~nz
- f-uaacog\~co\~us\~flex
- f-vailskishuttles\~co\~us
- f-wahkiakumferry\~wa\~us*
*An archived feed for whkiakuferry\~or\~us exists in atlas, but given this is WA and not OR, even though likely the same service in practice, I created a new entry.
Update URL:
- f-newburgh\~bus
- …
> Add batch of feed updates from Trillium

- feeds/transportgzm.pl.dmfr.json
Hello! 👋
`ZTM TransportGZM` is a public transport organization based in the Silesian Voivodeship, Poland. They manage buses, trams, trolleybuses and bikes. 
ZTM is the organization that governs it, "[TransportGZM](https://transportgzm.pl)" is a brand under which they run busses/trams/trolleybuses, and brand "[TransportGZM MetroRower](https://metrorower.transportgzm.pl/)" is for bikes. That's the reason I picked `o-transport~gzm~pl` and `f-transport~gzm~pl`/`o-transport~gzm~pl~tf`
This PR adds ZTM TransportGZM GTFS and GTFS-RT.
- The GTFS-RT has a static URL. Licensed under CC-BY-4.0
- The GTFS doesn't have a static URL. I [created an issue here](https://github.com/transitland/transitland-atlas/issues/1369) but got no response, so I just went with creating a mirror for their data. Data is …
> Add PL Silesian buses (Transport GZM)

- feeds/mobilis.pt.dmfr.json
This is the official feed for the Leiria Mobilis service.
We don't have a better (non-Google Drive) URL at hand.  This is the very same URL that sources Google Maps.
I do have the authorization to publish it under this license.
Cheers,
Cláudio
> Mobilis Leiria (Portugal)

- feeds/cimrl.pt.dmfr.json
This is the official feed for CIM Leiria / Rodoviária do Lis.
We don't have a better (non-Google Drive) URL at hand.  This is the very same URL that sources Google Maps.
I do have the authorization to publish it under this license.
The branding of the operation is "Rodoviária do Lis"; perhaps we should have that as an explicit feed name; what do you think? 
Cheers,
Cláudio
> CIM Leiria / Rodoviária do Lis (Portugal)

- feeds/baltimorecity.gov.dmfr.json
The current Charm City Circulator (Baltimore, MD) [feed](https://www.transit.land/operators/o-dqcx8-charmcitycirculator#routes) only has 4 routes - it is missing [the new Cherry Route](https://baltimorebeat.com/charm-city-circulator-adds-cherry-hill-route-connecting-the-neighborhood-to-downtown/).
I found a feed on Baltimore City's DOT's website with this [new route here](https://transportation.baltimorecity.gov/charm-city-circulator/developer-resources). I have updated `static_current` to point to this new download URL, and added the previously used URL to `static_historic`. I don't see any other relevant changes in the feed, either
For reference: old feed's `routes.txt` on the left, new feed's `routes.txt` on the right
> Charm City Circulator - Baltimore, MD

- feeds/oregon-gtfs.com.dmfr.json
https://www.portlandmercury.com/news/2019/12/17/27661589/central-eastsides-shuttle-has-shut-down
> Water Ave Shuttle shut down in 2019

- feeds/cadavl.com.dmfr.json
Greenlink GTFS-RT feeds were removed when updating the outdated static feeds. The new URLs are updated and current.
> Re-add Greenlink GTFS-RT feeds

- feeds/nationalrtap.org.dmfr.json
I am updating Nashua Transit System's GTFS static URL as Swiftly (my org) is now managing their GTFS static and will be supplying their GTFS-RT data soon. I have updated the nationalrtap.org file as that is where the NTS info lived previously, but lmk if I should create a new separate feed for NTS.
> Update Nashua Transit System GTFS-static URL 

- feeds/jizdnirady.pmdp.cz.dmfr.json
Today, after contacting the administrators, an informational text was added to the open data of Pilsen's website regarding the license on GTFS data. Such should now be reflected in the DMFR file.
> Add license in jizdnirady.pmdp.cz.dmfr.json 

- feeds/zditm.szczecin.pl.dmfr.json
GTFS data for ZDiTM Szczecin (Poland) are now [published under the CC0 license](https://www.zditm.szczecin.pl/en/zditm/for-developers/gtfs):
> The data are provided free of charge under the [CC0 1.0 licence](https://creativecommons.org/publicdomain/zero/1.0/), for use in any context, with no prior notification required.
> License change for ZDiTM Szczecin (Poland)

- feeds/hamilton.ca.dmfr.json
The link marked as current on the feed's page is dead: https://www.transit.land/feeds/f-dpxj-hamiltonstreetrailway
This replaces and updates it.
> Update Hamilton Street Railway GTFS current link

- feeds/transport.act.gov.au.dmfr.json
self-explanatory, fixes the DMFR file for Transport Canberra to point towards their new platform as described [here](https://www.transport.act.gov.au/contact-us/information-for-developers).
> Transport Canberra update
